library(usethis)
use_package("shiny", "Depends", "1.5.0")
use_package("spsUtil", "Depends")
use_package("htmltools")
use_package("bsplus")
use_package("assertthat")
use_package("stringr")
use_package("glue", min_version = "1.4.0")
use_package("magrittr")
use_package("bsplus")
use_package("shinyFiles")
use_package("shinyWidgets")
use_package("shinydashboardPlus", min_version = "2.0.0")
use_package("shinytoastr")
use_package("shinyAce")
use_package("shinydashboard")
use_package("shinyjqui")
use_package("vroom")
use_package("dplyr")
use_package("utils")
