library(usethis)
use_package("shiny", "Depends", "1.5.0")
use_package("spsUtil", "Suggests", "0.1.2")
use_package("htmltools")
use_package("assertthat")
use_package("stringr")
use_package("glue", min_version = "1.4.0")
use_package("magrittr")
use_package("shinyWidgets", type = "Suggests")
use_package("shinytoastr")
use_package("shinyAce")
use_package("shinyjqui", type = "")
use_package("utils")
use_package("R6")
use_package("crayon")
